### ISSUE TITLE
How do I interpret output structures?

### ISSUE THREAD

**Issue by Lila14** [multicom-toolbox/Chromosome3D#1]
My input file has 3350 rows representing 3350 loci. But the output PDB structure has 6065 "atoms". How do the atoms relate to loci?

**Comment by badriadhikari** [comment]
Hello Lila, thank you for trying our tool. First of all, Chromosome3D may not be able to handle more than around 1000 beads. Second, the number of atoms in the 3D structure must equal the number of beads in the input. Would you mind running the program again with much fewer beads (say 100 or 200) and see what happens. If it still does not work, please attach the input and output and we should be able to fix it.

**Comment by Lila14** [comment]
Yes it worked for 342 loci.

**Comment by Lila14** [comment]
Here is the output for 3350 loci. The file is too big to attach. 

./chromosome3D.pl -i input/GM12878_combined_22_10kb.txt -o output_models/chr22_10kb -m 1

Start Time : Wed Apr  5 10:38:45 2017 [./chromosome3D.pl]
Input      : input/GM12878_combined_22_10kb.txt
Output Dir : output_models/chr22_10kb
Scaling(K) : 11
Alpha      : 0.5
Effective Conversion Equation is : D = 11/[(IF^0.5)*(avg of IF^0.5)]
L          : 3350
Restraints : 3395968 lines in tbl file

(A) Build extended mtf and pdb..
(B) Build models using CNS dgsa..
Starting job [./job.sh > job.log]
(C) Assess models..

NOE_SATISFIED(±0.5A)  SUM_OF_DEVIATIONS>= 0.2  PDB
./GM12878_combined_22_10kb_1.pdb does not have 1002 CA
 at ./chromosome3D.pl line 546
        main::ssnoe_tbl_min_pdb_dist('contact.tbl', './GM12878_combined_22_10kb_1.pdb') called at ./chromosome3D.pl line 457
        main::count_satisfied_tbl_rows('./GM12878_combined_22_10kb_1.pdb', 'contact.tbl', 'noe') called at ./chromosome3D.pl line 807
        main::assess_dgsa() called at ./chromosome3D.pl line 106

**Comment by badriadhikari** [comment]
Hey Lila,
Yes, reading this log file I see that the program at step (C) is looking for a PDB file at atom 1002 loci, which it is unable to find. Our method is not tested to handle more than around 1000 points. It must have failed somewhere in the middle. You can try to scale up/down your interaction frequency input, and run the program. For eg. treat every 10 points as one point, and finally have around 300 points. Hope this helps.

**Comment by Lila14** [comment]
Thank you
